### ISSUE TITLE
Is there any way to fetch data before rendering?

### ISSUE THREAD

**Issue by juincc0** [ju5td0m7m1nd/react-ssr-template#1]
Hey, thanks for releasing this template. Just wondering if it's possible to fetch data before rendering.

And I also suggest providing an example app for demo ;) If you need help, I can make a PR.

**Comment by ju5td0m7m1nd** [comment]
Hi, glad to see your comment.

Yep, it can surely fetch data before rendering.

If I have to fetch data from others api as the initial state, 
I will use Request and put render function in the callback function.

I'm not sure whether I misunderstand your question :(

Welcome any PR to make this repo more complete  : D

**Comment by juincc0** [comment]
Glad to see your reply! I guess the fetching function is not in the code base now? I have implemented similar stuff in some projects but not sure if it goes well with the code base 🤔 

And I think this repo itself is an example 😎  Maybe adding more documentation? What do you think?

**Comment by ju5td0m7m1nd** [comment]
Yep, it is a very simple initial state for now.
Maybe we can put some fetching function as an example in this template!
